version: '3'
services:
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: ./django-api/.env
    restart: always

  api:
    container_name: djangoapp
    restart: always
    build:
      context: ./django-api
    ports:
      - "8000:8002"  # Проброс порта для бэкенда
    command: bash -c "python manage.py runserver 0.0.0.0:8002"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./
    ports:
      - "5000:5002"  # Проброс порта для фронтенда
    command: npm start
    depends_on:
      - api
